import { Statics } from '../interfaces/statics';
import defaultCurrencies from '../../../tests/helpers/data/currencies';

export const defaultStatics: Statics = {
  banks: [],
  bulk_updates: {},
  license_key: '',
  currencies: defaultCurrencies as any,
  countries: [
    {
      id: '840',
      capital: 'Washington',
      citizenship: 'American',
      country_code: '1',
      currency: 'US Dollar',
      currency_code: 'USD',
      currency_sub_unit: 'cent',
      full_name: 'United States of America',
      iso_3166_2: 'US',
      iso_3166_3: 'USA',
      name: 'United States',
      region_code: '021',
      sub_region_code: '021',
      eea: false,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ',',
      decimal_separator: '.',
    },
    {
      id: '826',
      capital: 'London',
      citizenship: 'British',
      country_code: '44',
      currency: 'British Pound',
      currency_code: 'GBP',
      currency_sub_unit: 'pence',
      full_name: 'United Kingdom of Great Britain and Northern Ireland',
      iso_3166_2: 'GB',
      iso_3166_3: 'GBR',
      name: 'United Kingdom',
      region_code: '150',
      sub_region_code: '154',
      eea: false,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ',',
      decimal_separator: '.',
    },
    {
      id: '124',
      capital: 'Ottawa',
      citizenship: 'Canadian',
      country_code: '1',
      currency: 'Canadian Dollar',
      currency_code: 'CAD',
      currency_sub_unit: 'cent',
      full_name: 'Canada',
      iso_3166_2: 'CA',
      iso_3166_3: 'CAN',
      name: 'Canada',
      region_code: '021',
      sub_region_code: '021',
      eea: false,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ',',
      decimal_separator: '.',
    },
    {
      id: '36',
      capital: 'Canberra',
      citizenship: 'Australian',
      country_code: '61',
      currency: 'Australian Dollar',
      currency_code: 'AUD',
      currency_sub_unit: 'cent',
      full_name: 'Commonwealth of Australia',
      iso_3166_2: 'AU',
      iso_3166_3: 'AUS',
      name: 'Australia',
      region_code: '009',
      sub_region_code: '053',
      eea: false,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ',',
      decimal_separator: '.',
    },
    {
      id: '276',
      capital: 'Berlin',
      citizenship: 'German',
      country_code: '49',
      currency: 'Euro',
      currency_code: 'EUR',
      currency_sub_unit: 'cent',
      full_name: 'Federal Republic of Germany',
      iso_3166_2: 'DE',
      iso_3166_3: 'DEU',
      name: 'Germany',
      region_code: '150',
      sub_region_code: '155',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: '.',
      decimal_separator: ',',
    },
    {
      id: '250',
      capital: 'Paris',
      citizenship: 'French',
      country_code: '33',
      currency: 'Euro',
      currency_code: 'EUR',
      currency_sub_unit: 'cent',
      full_name: 'French Republic',
      iso_3166_2: 'FR',
      iso_3166_3: 'FRA',
      name: 'France',
      region_code: '150',
      sub_region_code: '155',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ' ',
      decimal_separator: ',',
    },
    {
      id: '724',
      capital: 'Madrid',
      citizenship: 'Spanish',
      country_code: '34',
      currency: 'Euro',
      currency_code: 'EUR',
      currency_sub_unit: 'cent',
      full_name: 'Kingdom of Spain',
      iso_3166_2: 'ES',
      iso_3166_3: 'ESP',
      name: 'Spain',
      region_code: '150',
      sub_region_code: '039',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: '.',
      decimal_separator: ',',
    },
    {
      id: '380',
      capital: 'Rome',
      citizenship: 'Italian',
      country_code: '39',
      currency: 'Euro',
      currency_code: 'EUR',
      currency_sub_unit: 'cent',
      full_name: 'Italian Republic',
      iso_3166_2: 'IT',
      iso_3166_3: 'ITA',
      name: 'Italy',
      region_code: '150',
      sub_region_code: '039',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: '.',
      decimal_separator: ',',
    },
    {
      id: '528',
      capital: 'Amsterdam',
      citizenship: 'Dutch',
      country_code: '31',
      currency: 'Euro',
      currency_code: 'EUR',
      currency_sub_unit: 'cent',
      full_name: 'Kingdom of the Netherlands',
      iso_3166_2: 'NL',
      iso_3166_3: 'NLD',
      name: 'Netherlands',
      region_code: '150',
      sub_region_code: '155',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: '.',
      decimal_separator: ',',
    },
    {
      id: '756',
      capital: 'Bern',
      citizenship: 'Swiss',
      country_code: '41',
      currency: 'Swiss Franc',
      currency_code: 'CHF',
      currency_sub_unit: 'rappen',
      full_name: 'Swiss Confederation',
      iso_3166_2: 'CH',
      iso_3166_3: 'CHE',
      name: 'Switzerland',
      region_code: '150',
      sub_region_code: '155',
      eea: false,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: "'",
      decimal_separator: '.',
    },
    {
      id: '356',
      capital: 'New Delhi',
      citizenship: 'Indian',
      country_code: '91',
      currency: 'Indian Rupee',
      currency_code: 'INR',
      currency_sub_unit: 'paisa',
      full_name: 'Republic of India',
      iso_3166_2: 'IN',
      iso_3166_3: 'IND',
      name: 'India',
      region_code: '142',
      sub_region_code: '034',
      eea: false,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ',',
      decimal_separator: '.',
    },
    {
      id: '392',
      capital: 'Tokyo',
      citizenship: 'Japanese',
      country_code: '81',
      currency: 'Japanese Yen',
      currency_code: 'JPY',
      currency_sub_unit: 'sen',
      full_name: 'Japan',
      iso_3166_2: 'JP',
      iso_3166_3: 'JPN',
      name: 'Japan',
      region_code: '142',
      sub_region_code: '030',
      eea: false,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ',',
      decimal_separator: '.',
    },
    {
      id: '702',
      capital: 'Singapore',
      citizenship: 'Singaporean',
      country_code: '65',
      currency: 'Singapore Dollar',
      currency_code: 'SGD',
      currency_sub_unit: 'cent',
      full_name: 'Republic of Singapore',
      iso_3166_2: 'SG',
      iso_3166_3: 'SGP',
      name: 'Singapore',
      region_code: '142',
      sub_region_code: '035',
      eea: false,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ',',
      decimal_separator: '.',
    },
    {
      id: '554',
      capital: 'Wellington',
      citizenship: 'New Zealander',
      country_code: '64',
      currency: 'New Zealand Dollar',
      currency_code: 'NZD',
      currency_sub_unit: 'cent',
      full_name: 'New Zealand',
      iso_3166_2: 'NZ',
      iso_3166_3: 'NZL',
      name: 'New Zealand',
      region_code: '009',
      sub_region_code: '053',
      eea: false,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ',',
      decimal_separator: '.',
    },
    {
      id: '372',
      capital: 'Dublin',
      citizenship: 'Irish',
      country_code: '353',
      currency: 'Euro',
      currency_code: 'EUR',
      currency_sub_unit: 'cent',
      full_name: 'Ireland',
      iso_3166_2: 'IE',
      iso_3166_3: 'IRL',
      name: 'Ireland',
      region_code: '150',
      sub_region_code: '154',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ',',
      decimal_separator: '.',
    },
    {
      id: '752',
      capital: 'Stockholm',
      citizenship: 'Swedish',
      country_code: '46',
      currency: 'Swedish Krona',
      currency_code: 'SEK',
      currency_sub_unit: 'öre',
      full_name: 'Kingdom of Sweden',
      iso_3166_2: 'SE',
      iso_3166_3: 'SWE',
      name: 'Sweden',
      region_code: '150',
      sub_region_code: '154',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: true,
      thousand_separator: ' ',
      decimal_separator: ',',
    },
    {
      id: '578',
      capital: 'Oslo',
      citizenship: 'Norwegian',
      country_code: '47',
      currency: 'Norwegian Krone',
      currency_code: 'NOK',
      currency_sub_unit: 'øre',
      full_name: 'Kingdom of Norway',
      iso_3166_2: 'NO',
      iso_3166_3: 'NOR',
      name: 'Norway',
      region_code: '150',
      sub_region_code: '154',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: true,
      thousand_separator: ' ',
      decimal_separator: ',',
    },
    {
      id: '208',
      capital: 'Copenhagen',
      citizenship: 'Danish',
      country_code: '45',
      currency: 'Danish Krone',
      currency_code: 'DKK',
      currency_sub_unit: 'øre',
      full_name: 'Kingdom of Denmark',
      iso_3166_2: 'DK',
      iso_3166_3: 'DNK',
      name: 'Denmark',
      region_code: '150',
      sub_region_code: '154',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: true,
      thousand_separator: '.',
      decimal_separator: ',',
    },
    {
      id: '246',
      capital: 'Helsinki',
      citizenship: 'Finnish',
      country_code: '358',
      currency: 'Euro',
      currency_code: 'EUR',
      currency_sub_unit: 'cent',
      full_name: 'Republic of Finland',
      iso_3166_2: 'FI',
      iso_3166_3: 'FIN',
      name: 'Finland',
      region_code: '150',
      sub_region_code: '154',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ' ',
      decimal_separator: ',',
    },
    {
      id: '56',
      capital: 'Brussels',
      citizenship: 'Belgian',
      country_code: '32',
      currency: 'Euro',
      currency_code: 'EUR',
      currency_sub_unit: 'cent',
      full_name: 'Kingdom of Belgium',
      iso_3166_2: 'BE',
      iso_3166_3: 'BEL',
      name: 'Belgium',
      region_code: '150',
      sub_region_code: '155',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: '.',
      decimal_separator: ',',
    },
    {
      id: '40',
      capital: 'Vienna',
      citizenship: 'Austrian',
      country_code: '43',
      currency: 'Euro',
      currency_code: 'EUR',
      currency_sub_unit: 'cent',
      full_name: 'Republic of Austria',
      iso_3166_2: 'AT',
      iso_3166_3: 'AUT',
      name: 'Austria',
      region_code: '150',
      sub_region_code: '155',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: '.',
      decimal_separator: ',',
    },
    {
      id: '620',
      capital: 'Lisbon',
      citizenship: 'Portuguese',
      country_code: '351',
      currency: 'Euro',
      currency_code: 'EUR',
      currency_sub_unit: 'cent',
      full_name: 'Portuguese Republic',
      iso_3166_2: 'PT',
      iso_3166_3: 'PRT',
      name: 'Portugal',
      region_code: '150',
      sub_region_code: '039',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ' ',
      decimal_separator: ',',
    },
    {
      id: '616',
      capital: 'Warsaw',
      citizenship: 'Polish',
      country_code: '48',
      currency: 'Polish Zloty',
      currency_code: 'PLN',
      currency_sub_unit: 'grosz',
      full_name: 'Republic of Poland',
      iso_3166_2: 'PL',
      iso_3166_3: 'POL',
      name: 'Poland',
      region_code: '150',
      sub_region_code: '151',
      eea: true,
      swap_postal_code: false,
      swap_currency_symbol: true,
      thousand_separator: ' ',
      decimal_separator: ',',
    },
    {
      id: '484',
      capital: 'Mexico City',
      citizenship: 'Mexican',
      country_code: '52',
      currency: 'Mexican Peso',
      currency_code: 'MXN',
      currency_sub_unit: 'centavo',
      full_name: 'United Mexican States',
      iso_3166_2: 'MX',
      iso_3166_3: 'MEX',
      name: 'Mexico',
      region_code: '019',
      sub_region_code: '013',
      eea: false,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ',',
      decimal_separator: '.',
    },
    {
      id: '76',
      capital: 'Brasília',
      citizenship: 'Brazilian',
      country_code: '55',
      currency: 'Brazilian Real',
      currency_code: 'BRL',
      currency_sub_unit: 'centavo',
      full_name: 'Federative Republic of Brazil',
      iso_3166_2: 'BR',
      iso_3166_3: 'BRA',
      name: 'Brazil',
      region_code: '019',
      sub_region_code: '005',
      eea: false,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: '.',
      decimal_separator: ',',
    },
    {
      id: '710',
      capital: 'Pretoria',
      citizenship: 'South African',
      country_code: '27',
      currency: 'South African Rand',
      currency_code: 'ZAR',
      currency_sub_unit: 'cent',
      full_name: 'Republic of South Africa',
      iso_3166_2: 'ZA',
      iso_3166_3: 'ZAF',
      name: 'South Africa',
      region_code: '002',
      sub_region_code: '018',
      eea: false,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ',',
      decimal_separator: '.',
    },
    {
      id: '784',
      capital: 'Abu Dhabi',
      citizenship: 'Emirati',
      country_code: '971',
      currency: 'UAE Dirham',
      currency_code: 'AED',
      currency_sub_unit: 'fils',
      full_name: 'United Arab Emirates',
      iso_3166_2: 'AE',
      iso_3166_3: 'ARE',
      name: 'United Arab Emirates',
      region_code: '142',
      sub_region_code: '145',
      eea: false,
      swap_postal_code: false,
      swap_currency_symbol: false,
      thousand_separator: ',',
      decimal_separator: '.',
    },
  ],
  date_formats: [
    {
      id: '1',
      format: 'YYYY-MM-DD',
      format_dart: 'yyyy-MM-dd',
      format_moment: 'YYYY-MM-DD',
    },
    {
      id: '2',
      format: 'DD/MM/YYYY',
      format_dart: 'dd/MM/yyyy',
      format_moment: 'DD/MM/YYYY',
    },
    {
      id: '3',
      format: 'MM/DD/YYYY',
      format_dart: 'MM/dd/yyyy',
      format_moment: 'MM/DD/YYYY',
    },
    {
      id: '4',
      format: 'DD.MM.YYYY',
      format_dart: 'dd.MM.yyyy',
      format_moment: 'DD.MM.YYYY',
    },
    {
      id: '5',
      format: 'YYYY/MM/DD',
      format_dart: 'yyyy/MM/dd',
      format_moment: 'YYYY/MM/DD',
    },
    {
      id: '6',
      format: 'D/M/YYYY',
      format_dart: 'd/M/yyyy',
      format_moment: 'D/M/YYYY',
    },
    {
      id: '7',
      format: 'D-M-YYYY',
      format_dart: 'd-M-yyyy',
      format_moment: 'D-M-YYYY',
    },
  ],
  datetime_formats: [
    {
      id: '1',
      format: 'YYYY-MM-DD HH:mm',
      format_dart: 'yyyy-MM-dd HH:mm',
      format_moment: 'YYYY-MM-DD HH:mm',
    },
    {
      id: '2',
      format: 'DD/MM/YYYY HH:mm',
      format_dart: 'dd/MM/yyyy HH:mm',
      format_moment: 'DD/MM/YYYY HH:mm',
    },
    {
      id: '3',
      format: 'MM/DD/YYYY hh:mm a',
      format_dart: 'MM/dd/yyyy hh:mm a',
      format_moment: 'MM/DD/YYYY hh:mm a',
    },
    {
      id: '4',
      format: 'DD.MM.YYYY HH:mm',
      format_dart: 'dd.MM.yyyy HH:mm',
      format_moment: 'DD.MM.YYYY HH:mm',
    },
  ],
  gateways: [],
  industries: [
    { id: '1', name: 'Accounting & Legal' },
    { id: '2', name: 'Advertising & Marketing' },
    { id: '3', name: 'Aerospace & Defense' },
    { id: '4', name: 'Automotive' },
    { id: '5', name: 'Construction & Architecture' },
    { id: '6', name: 'Consulting & Professional Services' },
    { id: '7', name: 'Education' },
    { id: '8', name: 'Entertainment & Media' },
    { id: '9', name: 'Financial Services' },
    { id: '10', name: 'Food & Beverage' },
    { id: '11', name: 'Healthcare & Medical' },
    { id: '12', name: 'Information Technology' },
    { id: '13', name: 'Manufacturing' },
    { id: '14', name: 'Real Estate' },
    { id: '15', name: 'Retail & Consumer Goods' },
    { id: '16', name: 'Software & Internet' },
    { id: '17', name: 'Telecommunications' },
    { id: '18', name: 'Transportation & Logistics' },
    { id: '19', name: 'Other' },
  ],
  languages: [
    { id: '1', name: 'English', locale: 'en' },
    { id: '2', name: 'Spanish', locale: 'es' },
    { id: '3', name: 'French', locale: 'fr' },
    { id: '4', name: 'German', locale: 'de' },
    { id: '5', name: 'Italian', locale: 'it' },
    { id: '6', name: 'Dutch', locale: 'nl' },
    { id: '7', name: 'Portuguese (Brazil)', locale: 'pt_BR' },
    { id: '8', name: 'Portuguese (Portugal)', locale: 'pt_PT' },
    { id: '9', name: 'Japanese', locale: 'ja' },
    { id: '10', name: 'Chinese', locale: 'zh_TW' },
    { id: '11', name: 'Swedish', locale: 'sv' },
    { id: '12', name: 'Norwegian', locale: 'nb_NO' },
    { id: '13', name: 'Danish', locale: 'da' },
    { id: '14', name: 'Polish', locale: 'pl' },
    { id: '15', name: 'Russian', locale: 'ru_RU' },
  ],
  payment_types: [
    { id: '1', name: 'Apply Credit', gateway_type_id: null },
    { id: '2', name: 'Bank Transfer', gateway_type_id: null },
    { id: '3', name: 'Cash', gateway_type_id: null },
    { id: '4', name: 'Debit', gateway_type_id: null },
    { id: '5', name: 'ACH', gateway_type_id: null },
    { id: '6', name: 'Visa Card', gateway_type_id: null },
    { id: '7', name: 'MasterCard', gateway_type_id: null },
    { id: '8', name: 'American Express', gateway_type_id: null },
    { id: '9', name: 'Discover Card', gateway_type_id: null },
    { id: '10', name: 'PayPal', gateway_type_id: null },
    { id: '11', name: 'Check', gateway_type_id: null },
    { id: '12', name: 'Crypto', gateway_type_id: null },
  ],
  sizes: [
    { id: '1', name: '1 - 10' },
    { id: '2', name: '11 - 50' },
    { id: '3', name: '51 - 200' },
    { id: '4', name: '201 - 500' },
    { id: '5', name: '501 - 1,000' },
    { id: '6', name: '1000+' },
  ],
  timezones: [
    { id: '1', name: 'UTC', location: 'UTC', utc_offset: 0 },
    {
      id: '2',
      name: 'America/New_York (EST/EDT)',
      location: 'America/New_York',
      utc_offset: -18000,
    },
    {
      id: '3',
      name: 'America/Chicago (CST/CDT)',
      location: 'America/Chicago',
      utc_offset: -21600,
    },
    {
      id: '4',
      name: 'America/Denver (MST/MDT)',
      location: 'America/Denver',
      utc_offset: -25200,
    },
    {
      id: '5',
      name: 'America/Los_Angeles (PST/PDT)',
      location: 'America/Los_Angeles',
      utc_offset: -28800,
    },
    {
      id: '6',
      name: 'Europe/London (GMT/BST)',
      location: 'Europe/London',
      utc_offset: 0,
    },
    {
      id: '7',
      name: 'Europe/Paris (CET/CEST)',
      location: 'Europe/Paris',
      utc_offset: 3600,
    },
    {
      id: '8',
      name: 'Europe/Berlin (CET/CEST)',
      location: 'Europe/Berlin',
      utc_offset: 3600,
    },
    {
      id: '9',
      name: 'Asia/Tokyo (JST)',
      location: 'Asia/Tokyo',
      utc_offset: 32400,
    },
    {
      id: '10',
      name: 'Asia/Shanghai (CST)',
      location: 'Asia/Shanghai',
      utc_offset: 28800,
    },
    {
      id: '11',
      name: 'Asia/Singapore (SGT)',
      location: 'Asia/Singapore',
      utc_offset: 28800,
    },
    {
      id: '12',
      name: 'Asia/Kolkata (IST)',
      location: 'Asia/Kolkata',
      utc_offset: 19800,
    },
    {
      id: '13',
      name: 'Australia/Sydney (AEST/AEDT)',
      location: 'Australia/Sydney',
      utc_offset: 36000,
    },
    {
      id: '14',
      name: 'America/Toronto (EST/EDT)',
      location: 'America/Toronto',
      utc_offset: -18000,
    },
    {
      id: '15',
      name: 'America/Sao_Paulo (BRT)',
      location: 'America/Sao_Paulo',
      utc_offset: -10800,
    },
    {
      id: '16',
      name: 'Asia/Dubai (GST)',
      location: 'Asia/Dubai',
      utc_offset: 14400,
    },
  ],
  templates: {
    invoice: { subject: '', body: '' },
    quote: { subject: '', body: '' },
    payment: { subject: '', body: '' },
    payment_partial: { subject: '', body: '' },
    reminder1: { subject: '', body: '' },
    reminder2: { subject: '', body: '' },
    reminder3: { subject: '', body: '' },
    reminder_endless: { subject: '', body: '' },
    statement: { subject: '', body: '' },
    credit: { subject: '', body: '' },
  },
};
